apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: interview-backend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/xoibsurferx/interview.git
    targetRevision: sre-prodlike-demo
    path: sre/charts/interview-backend

  destination:
    server: https://kubernetes.default.svc
    namespace: interview

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
