apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/xoibsurferx/interview.git
    targetRevision: master
    path: sre/system

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

